---
- tags: mullvad_client
  block:

    - name: Assert mullvad_client_account is set
      ansible.builtin.assert:
        that:
          - mullvad_client_account | length
        fail_msg: mullvad_client_account needs to be set

    - name: Gather required facts
      ansible.builtin.setup:
      when: ansible_os_family is undefined

    - name: Add Mullvad APT key
      become: true
      apt_key:
        url: https://repository.mullvad.net/deb/mullvad-keyring.asc
    - name: Add Mullvad APT repo
      become: true
      apt_repository:
        repo: 'deb https://repository.mullvad.net/deb/stable {{ ansible_distribution_release }} main'
        filename: mullvad
    - name: Install Mullvad-Vpn
      become: true
      apt:
        name:
          - mullvad-vpn
          - nftables
        state: latest
        update_cache: true

    # - name: Install Mullvad Client
    #   become: true
    #   vars:
    #     _app_urls:
    #       RedHat: https://mullvad.net/download/app/rpm/latest
    #       Debian: https://mullvad.net/download/app/deb/latest
    #   block:

    #     - name: Install Mullvad Client (Debian)
    #       ansible.builtin.apt:
    #         deb: '{{ _app_urls[ansible_os_family] }}'
    #       when: ansible_os_family == 'Debian'

    #     - name: Install Mullvad Client (RedHat)
    #       ansible.builtin.dnf:
    #         name: '{{ _app_urls[ansible_os_family] }}'
    #       when: ansible_os_family == 'RedHat'


    - name: Configure account
      ansible.builtin.command:
        cmd: mullvad account login {{ mullvad_client_account }}

    - name: Allow Lan Access
      ansible.builtin.command:
        cmd: mullvad lan set allow

    - name: Configure location
      ansible.builtin.command:
        cmd: mullvad relay set location {{ mullvad_client_location.country }} {{ mullvad_client_location.city }}
      when: 
        - mullvad_client_location.city is defined
        - mullvad_client_location.country is defined

    - name: Configure server
      ansible.builtin.command:
        cmd: mullvad relay set hostname {{ mullvad_client_server }}
      when: mullvad_client_server | length

    - name: Configure DNS
      ansible.builtin.command:
        cmd: mullvad dns set {{ _custom_or_default }} {{ mullvad_client_dns }} {{ _blocklists }}
      vars:
        _custom_or_default: "{{ '' if mullvad_client_dns == 'default' else 'custom' }}"
        _blocklists: >-
          {% if mullvad_client_dns == 'default' %}
          {% for _blocklist_type in mullvad_client_dns_block %}
          --block-{{ _blocklist_type }}
          {% endfor %}
          {% endif %}

    - name: Exclude programs
      ansible.builtin.command:
        cmd: mullvad-exclude {{ item }}
      loop: "{{ mullvad_client_exclude }}"

    - name: Copy Port Rules
      copy:
        src: "../docker/torrents/wireguard"
        dest: "/home/feoin"
        owner: feoin
        group: users

    - name: Allow Ports through Wireguard
      command: "sudo nft -f /home/feoin/wireguard/config/excludePorts.rules"

    - name: Configure auto-connect
      ansible.builtin.command:
        cmd: mullvad auto-connect set {{ onOff }}
      vars:
        onOff: "{{ 'on' if mullvad_client_auto_connect else 'off' }}"

    - name: Ensure client is connected
      ansible.builtin.command:
        cmd: mullvad connect
      when: mullvad_client_auto_connect
